spring.application.name=backend

# JWT Config
virtualpet.jwt.secret=${JWT_SECRET:dGhpcy1pcy1hLXZlcnktc2VjdXJlLWtleS1mb3Itand0LXRva2Vucy12aXJ0dWFscGV0}
virtualpet.jwt.expirationMs=86400000

# Database config
spring.datasource.url=${DB_URL:jdbc:h2:mem:virtualpetdb;INIT=CREATE SCHEMA IF NOT EXISTS "CATALOG"\\;CREATE SCHEMA IF NOT EXISTS "AUTH"}
spring.datasource.username=${DB_USER:sa}
spring.datasource.password=${DB_PASSWORD:password}
spring.datasource.driver-class-name=${DB_DRIVER:org.h2.Driver}
spring.jpa.hibernate.ddl-auto=update

# Redis config
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

# Mail config
spring.mail.host=localhost
spring.mail.port=1025
